name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip install buildozer cython==0.29.33 kivy
      - name: Build APK
        run: |
          buildozer init
          sed -i 's/title = My Application/title = Team Nezarat/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = teamnezarat/' buildozer.spec
          sed -i 's/#icon.filename =/icon.filename = logo.png/' buildozer.spec
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,requests,urllib3,certifi,chardet,idna/' buildozer.spec
          yes | buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Team-Nezarat-App
          path: bin/*.apk
